import type { IconifyJSON } from '@iconify/types'

// GENERATED by scripts/generate-icon-data.mjs — do not hand-edit.
// Re-run `pnpm generate:icons` after changing lib/icons/icon-map.ts.
import AddCircleOutlineRoundedIcon from '@iconify-icons/material-symbols/add-circle-outline-rounded'
import AddOutlineRoundedIcon from '@iconify-icons/material-symbols/add-outline-rounded'
import ApartmentOutlineRoundedIcon from '@iconify-icons/material-symbols/apartment-outline-rounded'
import ArchiveOutlineRoundedIcon from '@iconify-icons/material-symbols/archive-outline-rounded'
import ArrowBackOutlineRoundedIcon from '@iconify-icons/material-symbols/arrow-back-outline-rounded'
import ArrowDownwardOutlineRoundedIcon from '@iconify-icons/material-symbols/arrow-downward-outline-rounded'
import ArrowForwardOutlineRoundedIcon from '@iconify-icons/material-symbols/arrow-forward-outline-rounded'
import ArrowOutwardOutlineRoundedIcon from '@iconify-icons/material-symbols/arrow-outward-outline-rounded'
import ArrowUpwardOutlineRoundedIcon from '@iconify-icons/material-symbols/arrow-upward-outline-rounded'
import AttachFileOutlineRoundedIcon from '@iconify-icons/material-symbols/attach-file-outline-rounded'
import AttachMoneyOutlineRoundedIcon from '@iconify-icons/material-symbols/attach-money-outline-rounded'
import AutoAwesomeOutlineRoundedIcon from '@iconify-icons/material-symbols/auto-awesome-outline-rounded'
import BarChartOutlineRoundedIcon from '@iconify-icons/material-symbols/bar-chart-outline-rounded'
import BoltOutlineRoundedIcon from '@iconify-icons/material-symbols/bolt-outline-rounded'
import BookOutlineRoundedIcon from '@iconify-icons/material-symbols/book-outline-rounded'
import BuildOutlineRoundedIcon from '@iconify-icons/material-symbols/build-outline-rounded'
import CalendarMonthOutlineRoundedIcon from '@iconify-icons/material-symbols/calendar-month-outline-rounded'
import CallOutlineRoundedIcon from '@iconify-icons/material-symbols/call-outline-rounded'
import CallReceivedOutlineRoundedIcon from '@iconify-icons/material-symbols/call-received-outline-rounded'
import CancelOutlineRoundedIcon from '@iconify-icons/material-symbols/cancel-outline-rounded'
import ChatOutlineRoundedIcon from '@iconify-icons/material-symbols/chat-outline-rounded'
import CheckCircleOutlineRoundedIcon from '@iconify-icons/material-symbols/check-circle-outline-rounded'
import CheckOutlineRoundedIcon from '@iconify-icons/material-symbols/check-outline-rounded'
import ChevronLeftOutlineRoundedIcon from '@iconify-icons/material-symbols/chevron-left-outline-rounded'
import ChevronRightOutlineRoundedIcon from '@iconify-icons/material-symbols/chevron-right-outline-rounded'
import CircleOutlineRoundedIcon from '@iconify-icons/material-symbols/circle-outline-rounded'
import CloseOutlineRoundedIcon from '@iconify-icons/material-symbols/close-outline-rounded'
import CreditCardOutlineRoundedIcon from '@iconify-icons/material-symbols/credit-card-outline-rounded'
import DarkModeOutlineRoundedIcon from '@iconify-icons/material-symbols/dark-mode-outline-rounded'
import DashboardOutlineRoundedIcon from '@iconify-icons/material-symbols/dashboard-outline-rounded'
import DateRangeOutlineRoundedIcon from '@iconify-icons/material-symbols/date-range-outline-rounded'
import DeleteOutlineRoundedIcon from '@iconify-icons/material-symbols/delete-outline-rounded'
import DescriptionOutlineRoundedIcon from '@iconify-icons/material-symbols/description-outline-rounded'
import DomainOutlineRoundedIcon from '@iconify-icons/material-symbols/domain-outline-rounded'
import DownloadOutlineRoundedIcon from '@iconify-icons/material-symbols/download-outline-rounded'
import DragIndicatorOutlineRoundedIcon from '@iconify-icons/material-symbols/drag-indicator-outline-rounded'
import EditOutlineRoundedIcon from '@iconify-icons/material-symbols/edit-outline-rounded'
import ErrorOutlineRoundedIcon from '@iconify-icons/material-symbols/error-outline-rounded'
import ExpandLessIcon from '@iconify-icons/material-symbols/expand-less'
import ExpandMoreIcon from '@iconify-icons/material-symbols/expand-more'
import FactCheckOutlineRoundedIcon from '@iconify-icons/material-symbols/fact-check-outline-rounded'
import FiberManualRecordOutlineRoundedIcon from '@iconify-icons/material-symbols/fiber-manual-record-outline-rounded'
import FilterAltOutlineRoundedIcon from '@iconify-icons/material-symbols/filter-alt-outline-rounded'
import GroupOutlineRoundedIcon from '@iconify-icons/material-symbols/group-outline-rounded'
import HelpOutlineRoundedIcon from '@iconify-icons/material-symbols/help-outline-rounded'
import HomeOutlineRoundedIcon from '@iconify-icons/material-symbols/home-outline-rounded'
import ImageOutlineRoundedIcon from '@iconify-icons/material-symbols/image-outline-rounded'
import InfoOutlineRoundedIcon from '@iconify-icons/material-symbols/info-outline-rounded'
import LeftPanelOpenOutlineRoundedIcon from '@iconify-icons/material-symbols/left-panel-open-outline-rounded'
import LightModeOutlineRoundedIcon from '@iconify-icons/material-symbols/light-mode-outline-rounded'
import LocationOnOutlineRoundedIcon from '@iconify-icons/material-symbols/location-on-outline-rounded'
import LockOutlineRoundedIcon from '@iconify-icons/material-symbols/lock-outline-rounded'
import LogoutOutlineRoundedIcon from '@iconify-icons/material-symbols/logout-outline-rounded'
import MailOutlineRoundedIcon from '@iconify-icons/material-symbols/mail-outline-rounded'
import MenuOutlineRoundedIcon from '@iconify-icons/material-symbols/menu-outline-rounded'
import MonitorOutlineRoundedIcon from '@iconify-icons/material-symbols/monitor-outline-rounded'
import MonitoringOutlineRoundedIcon from '@iconify-icons/material-symbols/monitoring-outline-rounded'
import MoodOutlineRoundedIcon from '@iconify-icons/material-symbols/mood-outline-rounded'
import MoreHorizOutlineRoundedIcon from '@iconify-icons/material-symbols/more-horiz-outline-rounded'
import MoreVertOutlineRoundedIcon from '@iconify-icons/material-symbols/more-vert-outline-rounded'
import NotificationsOutlineRoundedIcon from '@iconify-icons/material-symbols/notifications-outline-rounded'
import OpenInNewOutlineRoundedIcon from '@iconify-icons/material-symbols/open-in-new-outline-rounded'
import PaletteOutlineRoundedIcon from '@iconify-icons/material-symbols/palette-outline-rounded'
import PercentOutlineRoundedIcon from '@iconify-icons/material-symbols/percent-outline-rounded'
import PersonAddOutlineRoundedIcon from '@iconify-icons/material-symbols/person-add-outline-rounded'
import PersonOutlineRoundedIcon from '@iconify-icons/material-symbols/person-outline-rounded'
import PhotoCameraOutlineRoundedIcon from '@iconify-icons/material-symbols/photo-camera-outline-rounded'
import PieChartOutlineRoundedIcon from '@iconify-icons/material-symbols/pie-chart-outline-rounded'
import ProgressActivityOutlineRoundedIcon from '@iconify-icons/material-symbols/progress-activity-outline-rounded'
import ScheduleOutlineRoundedIcon from '@iconify-icons/material-symbols/schedule-outline-rounded'
import SearchOutlineRoundedIcon from '@iconify-icons/material-symbols/search-outline-rounded'
import SendOutlineRoundedIcon from '@iconify-icons/material-symbols/send-outline-rounded'
import SettingsOutlineRoundedIcon from '@iconify-icons/material-symbols/settings-outline-rounded'
import ShareOutlineRoundedIcon from '@iconify-icons/material-symbols/share-outline-rounded'
import ShieldOutlineRoundedIcon from '@iconify-icons/material-symbols/shield-outline-rounded'
import ShowChartOutlineRoundedIcon from '@iconify-icons/material-symbols/show-chart-outline-rounded'
import SmartphoneOutlineIcon from '@iconify-icons/material-symbols/smartphone-outline'
import StarOutlineRoundedIcon from '@iconify-icons/material-symbols/star-outline-rounded'
import TagOutlineRoundedIcon from '@iconify-icons/material-symbols/tag-outline-rounded'
import TargetOutlineRoundedIcon from '@iconify-icons/material-symbols/target-outline-rounded'
import ThermostatOutlineRoundedIcon from '@iconify-icons/material-symbols/thermostat-outline-rounded'
import ThumbUpOutlineRoundedIcon from '@iconify-icons/material-symbols/thumb-up-outline-rounded'
import TrendingDownOutlineRoundedIcon from '@iconify-icons/material-symbols/trending-down-outline-rounded'
import TrendingUpOutlineRoundedIcon from '@iconify-icons/material-symbols/trending-up-outline-rounded'
import UploadOutlineRoundedIcon from '@iconify-icons/material-symbols/upload-outline-rounded'
import VideocamOutlineRoundedIcon from '@iconify-icons/material-symbols/videocam-outline-rounded'
import VisibilityOffOutlineRoundedIcon from '@iconify-icons/material-symbols/visibility-off-outline-rounded'
import VisibilityOutlineRoundedIcon from '@iconify-icons/material-symbols/visibility-outline-rounded'
import WarningOutlineRoundedIcon from '@iconify-icons/material-symbols/warning-outline-rounded'
import WaterDropOutlineRoundedIcon from '@iconify-icons/material-symbols/water-drop-outline-rounded'
import WorkOutlineRoundedIcon from '@iconify-icons/material-symbols/work-outline-rounded'

const icons: Record<string, unknown> = {
  'add-circle-outline-rounded': AddCircleOutlineRoundedIcon,
  'add-outline-rounded': AddOutlineRoundedIcon,
  'apartment-outline-rounded': ApartmentOutlineRoundedIcon,
  'archive-outline-rounded': ArchiveOutlineRoundedIcon,
  'arrow-back-outline-rounded': ArrowBackOutlineRoundedIcon,
  'arrow-downward-outline-rounded': ArrowDownwardOutlineRoundedIcon,
  'arrow-forward-outline-rounded': ArrowForwardOutlineRoundedIcon,
  'arrow-outward-outline-rounded': ArrowOutwardOutlineRoundedIcon,
  'arrow-upward-outline-rounded': ArrowUpwardOutlineRoundedIcon,
  'attach-file-outline-rounded': AttachFileOutlineRoundedIcon,
  'attach-money-outline-rounded': AttachMoneyOutlineRoundedIcon,
  'auto-awesome-outline-rounded': AutoAwesomeOutlineRoundedIcon,
  'bar-chart-outline-rounded': BarChartOutlineRoundedIcon,
  'bolt-outline-rounded': BoltOutlineRoundedIcon,
  'book-outline-rounded': BookOutlineRoundedIcon,
  'build-outline-rounded': BuildOutlineRoundedIcon,
  'calendar-month-outline-rounded': CalendarMonthOutlineRoundedIcon,
  'call-outline-rounded': CallOutlineRoundedIcon,
  'call-received-outline-rounded': CallReceivedOutlineRoundedIcon,
  'cancel-outline-rounded': CancelOutlineRoundedIcon,
  'chat-outline-rounded': ChatOutlineRoundedIcon,
  'check-circle-outline-rounded': CheckCircleOutlineRoundedIcon,
  'check-outline-rounded': CheckOutlineRoundedIcon,
  'chevron-left-outline-rounded': ChevronLeftOutlineRoundedIcon,
  'chevron-right-outline-rounded': ChevronRightOutlineRoundedIcon,
  'circle-outline-rounded': CircleOutlineRoundedIcon,
  'close-outline-rounded': CloseOutlineRoundedIcon,
  'credit-card-outline-rounded': CreditCardOutlineRoundedIcon,
  'dark-mode-outline-rounded': DarkModeOutlineRoundedIcon,
  'dashboard-outline-rounded': DashboardOutlineRoundedIcon,
  'date-range-outline-rounded': DateRangeOutlineRoundedIcon,
  'delete-outline-rounded': DeleteOutlineRoundedIcon,
  'description-outline-rounded': DescriptionOutlineRoundedIcon,
  'domain-outline-rounded': DomainOutlineRoundedIcon,
  'download-outline-rounded': DownloadOutlineRoundedIcon,
  'drag-indicator-outline-rounded': DragIndicatorOutlineRoundedIcon,
  'edit-outline-rounded': EditOutlineRoundedIcon,
  'error-outline-rounded': ErrorOutlineRoundedIcon,
  'expand-less': ExpandLessIcon,
  'expand-more': ExpandMoreIcon,
  'fact-check-outline-rounded': FactCheckOutlineRoundedIcon,
  'fiber-manual-record-outline-rounded': FiberManualRecordOutlineRoundedIcon,
  'filter-alt-outline-rounded': FilterAltOutlineRoundedIcon,
  'group-outline-rounded': GroupOutlineRoundedIcon,
  'help-outline-rounded': HelpOutlineRoundedIcon,
  'home-outline-rounded': HomeOutlineRoundedIcon,
  'image-outline-rounded': ImageOutlineRoundedIcon,
  'info-outline-rounded': InfoOutlineRoundedIcon,
  'left-panel-open-outline-rounded': LeftPanelOpenOutlineRoundedIcon,
  'light-mode-outline-rounded': LightModeOutlineRoundedIcon,
  'location-on-outline-rounded': LocationOnOutlineRoundedIcon,
  'lock-outline-rounded': LockOutlineRoundedIcon,
  'logout-outline-rounded': LogoutOutlineRoundedIcon,
  'mail-outline-rounded': MailOutlineRoundedIcon,
  'menu-outline-rounded': MenuOutlineRoundedIcon,
  'monitor-outline-rounded': MonitorOutlineRoundedIcon,
  'monitoring-outline-rounded': MonitoringOutlineRoundedIcon,
  'mood-outline-rounded': MoodOutlineRoundedIcon,
  'more-horiz-outline-rounded': MoreHorizOutlineRoundedIcon,
  'more-vert-outline-rounded': MoreVertOutlineRoundedIcon,
  'notifications-outline-rounded': NotificationsOutlineRoundedIcon,
  'open-in-new-outline-rounded': OpenInNewOutlineRoundedIcon,
  'palette-outline-rounded': PaletteOutlineRoundedIcon,
  'percent-outline-rounded': PercentOutlineRoundedIcon,
  'person-add-outline-rounded': PersonAddOutlineRoundedIcon,
  'person-outline-rounded': PersonOutlineRoundedIcon,
  'photo-camera-outline-rounded': PhotoCameraOutlineRoundedIcon,
  'pie-chart-outline-rounded': PieChartOutlineRoundedIcon,
  'progress-activity-outline-rounded': ProgressActivityOutlineRoundedIcon,
  'schedule-outline-rounded': ScheduleOutlineRoundedIcon,
  'search-outline-rounded': SearchOutlineRoundedIcon,
  'send-outline-rounded': SendOutlineRoundedIcon,
  'settings-outline-rounded': SettingsOutlineRoundedIcon,
  'share-outline-rounded': ShareOutlineRoundedIcon,
  'shield-outline-rounded': ShieldOutlineRoundedIcon,
  'show-chart-outline-rounded': ShowChartOutlineRoundedIcon,
  'smartphone-outline': SmartphoneOutlineIcon,
  'star-outline-rounded': StarOutlineRoundedIcon,
  'tag-outline-rounded': TagOutlineRoundedIcon,
  'target-outline-rounded': TargetOutlineRoundedIcon,
  'thermostat-outline-rounded': ThermostatOutlineRoundedIcon,
  'thumb-up-outline-rounded': ThumbUpOutlineRoundedIcon,
  'trending-down-outline-rounded': TrendingDownOutlineRoundedIcon,
  'trending-up-outline-rounded': TrendingUpOutlineRoundedIcon,
  'upload-outline-rounded': UploadOutlineRoundedIcon,
  'videocam-outline-rounded': VideocamOutlineRoundedIcon,
  'visibility-off-outline-rounded': VisibilityOffOutlineRoundedIcon,
  'visibility-outline-rounded': VisibilityOutlineRoundedIcon,
  'warning-outline-rounded': WarningOutlineRoundedIcon,
  'water-drop-outline-rounded': WaterDropOutlineRoundedIcon,
  'work-outline-rounded': WorkOutlineRoundedIcon,
}

export const iconCollection = { prefix: 'material-symbols', icons } as unknown as IconifyJSON
