/**
 * Lucide name -> Iconify Material Symbols name.
 *
 * Names are kebab-case (Iconify's normalisation), NOT the snake_case used by
 * Google's Material Symbols font ligatures. `credit-card`, not `credit_card`.
 *
 * Style is `-outline-rounded` by default: Material Symbols defaults to filled,
 * which reads far heavier than the Lucide stroke icons being replaced.
 * ChevronDown/ChevronUp/Smartphone fall back because no outline-rounded
 * variant exists for them.
 *
 * Validated by scripts/verify-icon-map.mjs — run `pnpm verify:icons`.
 */
export const ICON_MAP = {
  Activity: 'monitoring-outline-rounded',
  AlertCircle: 'error-outline-rounded',
  AlertTriangle: 'warning-outline-rounded',
  Archive: 'archive-outline-rounded',
  ArrowDown: 'arrow-downward-outline-rounded',
  ArrowDownRight: 'call-received-outline-rounded',
  ArrowLeft: 'arrow-back-outline-rounded',
  ArrowRight: 'arrow-forward-outline-rounded',
  ArrowUp: 'arrow-upward-outline-rounded',
  ArrowUpRight: 'arrow-outward-outline-rounded',
  BarChart3: 'bar-chart-outline-rounded',
  Bell: 'notifications-outline-rounded',
  Book: 'book-outline-rounded',
  Briefcase: 'work-outline-rounded',
  Building: 'domain-outline-rounded',
  Building2: 'apartment-outline-rounded',
  Calendar: 'calendar-month-outline-rounded',
  CalendarDays: 'date-range-outline-rounded',
  Camera: 'photo-camera-outline-rounded',
  Check: 'check-outline-rounded',
  CheckCircle: 'check-circle-outline-rounded',
  CheckCircle2: 'check-circle-outline-rounded',
  ChevronDown: 'expand-more',
  ChevronLeft: 'chevron-left-outline-rounded',
  ChevronRight: 'chevron-right-outline-rounded',
  ChevronUp: 'expand-less',
  Circle: 'circle-outline-rounded',
  Clock: 'schedule-outline-rounded',
  CreditCard: 'credit-card-outline-rounded',
  DollarSign: 'attach-money-outline-rounded',
  Dot: 'fiber-manual-record-outline-rounded',
  Download: 'download-outline-rounded',
  Droplets: 'water-drop-outline-rounded',
  Edit: 'edit-outline-rounded',
  ExternalLink: 'open-in-new-outline-rounded',
  Eye: 'visibility-outline-rounded',
  EyeOff: 'visibility-off-outline-rounded',
  FileCheck: 'fact-check-outline-rounded',
  FileText: 'description-outline-rounded',
  Filter: 'filter-alt-outline-rounded',
  GripVertical: 'drag-indicator-outline-rounded',
  Hash: 'tag-outline-rounded',
  HelpCircle: 'help-outline-rounded',
  Home: 'home-outline-rounded',
  Image: 'image-outline-rounded',
  Info: 'info-outline-rounded',
  LayoutDashboard: 'dashboard-outline-rounded',
  LineChart: 'show-chart-outline-rounded',
  Loader2: 'progress-activity-outline-rounded',
  Lock: 'lock-outline-rounded',
  LogOut: 'logout-outline-rounded',
  Mail: 'mail-outline-rounded',
  MapPin: 'location-on-outline-rounded',
  Menu: 'menu-outline-rounded',
  MessageSquare: 'chat-outline-rounded',
  Monitor: 'monitor-outline-rounded',
  Moon: 'dark-mode-outline-rounded',
  MoreHorizontal: 'more-horiz-outline-rounded',
  MoreVertical: 'more-vert-outline-rounded',
  Palette: 'palette-outline-rounded',
  PanelLeft: 'left-panel-open-outline-rounded',
  Paperclip: 'attach-file-outline-rounded',
  PaperclipIcon: 'attach-file-outline-rounded',
  Percent: 'percent-outline-rounded',
  Phone: 'call-outline-rounded',
  PieChart: 'pie-chart-outline-rounded',
  Plus: 'add-outline-rounded',
  PlusCircle: 'add-circle-outline-rounded',
  Search: 'search-outline-rounded',
  Send: 'send-outline-rounded',
  SendIcon: 'send-outline-rounded',
  Settings: 'settings-outline-rounded',
  Share: 'share-outline-rounded',
  Shield: 'shield-outline-rounded',
  Smartphone: 'smartphone-outline',
  Smile: 'mood-outline-rounded',
  Sparkles: 'auto-awesome-outline-rounded',
  Star: 'star-outline-rounded',
  Sun: 'light-mode-outline-rounded',
  Target: 'target-outline-rounded',
  Thermometer: 'thermostat-outline-rounded',
  ThumbsUp: 'thumb-up-outline-rounded',
  Trash2: 'delete-outline-rounded',
  TrendingDown: 'trending-down-outline-rounded',
  TrendingUp: 'trending-up-outline-rounded',
  Upload: 'upload-outline-rounded',
  User: 'person-outline-rounded',
  UserPlus: 'person-add-outline-rounded',
  Users: 'group-outline-rounded',
  Video: 'videocam-outline-rounded',
  Wrench: 'build-outline-rounded',
  X: 'close-outline-rounded',
  XCircle: 'cancel-outline-rounded',
  Zap: 'bolt-outline-rounded',
} as const

export type IconName = keyof typeof ICON_MAP
